# Given sequence
ntr = "GAGTATACTTCACGTTTTGCGTCAATGAATATGTATTTCACCAATTTTGGTTACTCGACCTTGACCGCGAACCTCGTGGCTCTGGGAATTGATTTATAAAGAATTGAAGGAGGCCGTTGAGAGGTTCTACAGTCTGGCGTGGTAATAACAAGGTTGTGCACTACAGATCGCAAGACGCACGTGTAAATACGGACCATTGTTTACAACTGTAGATGTTGCCGCGGAAAGCCATCTGAGGACCTGCGCACGGTCACTGGAATAAGATGGGTTATATGAAGTGGGCTAGAATTTTTTTGGTGTACGTTCGGGGTCTGGCAGCGCGGGACTAAAAGACTATAGGGAATCTCAGTGGCTGACTCCGACTTATCCGGACACGAACCGCAAAAGTGCCCCGTGTGGCGGTTCATATCTAGCGTTGTTGTAGGGCTCACTTGCATTGCGGGCGAATGGGGATTTAACTTTGAAAGGCGCCATCAGAAATAACACCCACCTACAGAACAGTAATTATAGAAGACAAGAGGGAATCCCCCCCTGATTGCGCAGCCTATATCCCCGAGCCCACTTGACTTTATAAGGTGTGAGCATAAGAAAATTTGCCACCCGCTGTATAAAGAGGTGAAACGAATCACGCAGCGTTACTATTGTGTGTTCGCGATCCACTAAAGGGGCGGGCGTACAGAGCCCTACCTGCCCACGACGAGGGGGCGGTCTTCATCATCTCGTGTGCGTCGATGTAACGTATTAGGCCTTCACTTCGCTATCCCATCCGCCGACCCCTGGTCTTATTTGTGTATGTCACCGCAATTGGTTGTTAGCTCCGCAAACCGTACTCATGGGTGGAGAAGCCGACGAGATTCGGTGGCCATGTTAATTCGGTGCAATATTGGTTAGCGTCGTCAGGTTTGTGTGGGACTAGGACGCTAGAAGTCATAGAACTTCACGACGTTTTAGTCTCGTAGACTGGTATGATTGG"

# Counting A
A = 0
for letter in ntr:
    if letter == "A":
        A = A+1

# Counting C
C = 0
for letter in ntr:
    if letter == "C":
        C = C+1

# Counting G
G = 0
for letter in ntr:
    if letter == "G":
        G= G+1

# Counting T
T = 0
for letter in ntr:
    if letter == "T":
        T = T+1

# Printing Output
print (A, C, G, T)