# Problem
## In DNA strings, symbols 'A' and 'T' are complements of each other, as are 'C' and 'G'.
## The reverse complement of a DNA string s is the string sc formed by reversing the symbols of s, then taking the complement of each symbol (e.g., the reverse complement of "GTCA" is "TGAC").
## Given: A DNA string s of length at most 1000 bp.
## Return: The reverse complement sc of s.

# DNA sequence s

s = "AGAAGTGGGGCATAAACGCGATACCATCAAGGTTCGGTGCCTGAACCGTGGGGGAACCAGTAGCGTCCTTAAACTGGATCGCGGGACGACTCACGTAGCGGAAGGATTCCATCCCAGTACGGTGCGTCCAACCTCAAGTGTGAAATTTCGCCTAGCATCTCGGAAAACGTTCCGGCTGTCTCCAGGCCCACCAACGTCTTTCGAGTCCCTTATGTCGTGTTCAAAACATGGACGACGTAGACTACTACCGCCGCTACGCGTATGGTTTCTAAAATAGCCTATAAACAGGTTACGTGGTGTCCTACCTAAACGTACATACTAGCTAAACACACTCGGCGCTATACAAGCGGCGGAAAATTTCAGAATAGCTAAACGTTCGGGCCATGACCAAGACCGTGTCCACGGATAGTGGCGTTCCAAGTAATGATTTGGCAAACTTGAATTCACTACTGTTCACATCGATCGGCATAAACAATGGTCTGGTATTAGGCCCCCAACCCAGCCAGACTGCCAGAAATGCGCACTCCATTCCCTTGAATACCTTGCTAAACCACATAAATGAGAAATGTTGGAAGAATGCTAACGCAACCCTCGTATCGTAGGGGTCCCATAGACCTACATCATACGCGGCTTTCCACATATGAAAGATCACTATGATCCTATATGCAATCACGGCAAATCGCTTAACCTAGAACAGGCGACTGCTCTGAGTATGCATTTGAGTTTACGAGGGGGAACAAAGTACCAATGCAAAATCGTTTACTGGGGCAGTCTGTGTAGGATCTAAGTACGACGGCCTCGAAAGTGGGACCGCCATTTAGCACCTTTTTCGCGGCCAGGAGTAGTCTCAATGTAACGAATTAAAGTATCGTCTTGTGATCGCTCGGGAGATAGCTAAATTTAGTTAGCCTGATTCCCTCGTACCGGAGAAAGACTATGCAGGCTTCCCCACCAACAACCTACTTACCACCGCAGTGCGTGAGCCCAAGGA"

# defining complement function
def complement (x):
    if x == "A":
            return "T"
    elif x == "G":
             return "C"
    elif x == "C":
            return "G"
    elif x == "T":
            return "A"
    
# Making complement of s

sc = ""

for base in s:
    sc = sc + complement(base)

sc

# Reverse of sc

scr = sc[::-1]
scr